apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: rrazvandev/client
        env:
          - name: NODE_OPTIONS
            value: --max-old-space-size=8192
          - name: SERVER_URL_BASE
            value: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local
        resources:
          limits:
            memory: "500Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
  - name: client
    port: 3000
    targetPort: 3000
    protocol: TCP
