name: tests-payments
env:
  STRIPE_KEY: ${{ secrets.STRIPE_KEY }}

on:
  pull_request:
    paths:
      - 'payments/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Git checkout
       uses: actions/checkout@v2

     - name: Use Node 14.x
       uses: actions/setup-node@v1
       with:
          node-version: 14.x
     - name: Install Dependencies (prod)
       run: cd payments && npm install
     - name: Run Tests (JEST)
       run: npm run test:ci
       env:
          CI: true
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
          
      
