name: tests-tickets

on:
  pull_request:
    paths:
      - 'tickets/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Git checkout
       uses: actions/checkout@v2

     - name: Use Node 14.x
       uses: actions/setup-node@v1
       with:
          node-version: 14.x
     - name: Install Dependencies (ALL)
       run: cd tickets && npm install
     - name: Run Tests (JEST)
       run: cd tickets && npm run test:ci
       env:
          CI: true          
      
